// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlnfmejvjjstwkthnsha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbmZtZWp2ampzdHdrdGhuc2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTE2MTgsImV4cCI6MjA2NTQ2NzYxOH0.Eh7b1ronsTPyEhDIcMg8U-EpuWZJsh9SEdX9XfYoCbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);